name: Create GitHub Release

permissions:
  contents: write

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensure we have the latest code

      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          release_name: Release  # Name of the GitHub Release
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

  upload-assets:
    needs: create-release  # This job depends on create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload assets
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          # Example list of binaries to build and upload. Adjust as needed.
          bin: your_binary_name  # Comma-separated list of binary names to build and upload
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
